REGEX_SPECIFICATIONS = {
    "ReleaseTitleSpecification",
    "ReleaseGroupSpecification",
}

IMPLEMENTATION_TO_TAG_MAPPING = {
    "ReleaseTitleSpecification": "Release Title",
    "ResolutionSpecification": "Resolution",
    "SourceSpecification": "Source",
    "LanguageSpecification": "Language",
    "ReleaseGroupSpecification": "Release Group",
    "IndexerFlagSpecification": "Indexer Flag",
    "QualityModifierSpecification": "Quality Modifier",
    "ReleaseTypeSpecification": "Release Type",
}

IMPLEMENTATION_TO_CONDITION_TYPE = {
    "ReleaseTitleSpecification": "release_title",
    "ResolutionSpecification": "resolution",
    "SourceSpecification": "source",
    "LanguageSpecification": "language",
    "ReleaseGroupSpecification": "release_group",
    "IndexerFlagSpecification": "indexer_flag",
    "QualityModifierSpecification": "quality_modifier",
    "ReleaseTypeSpecification": "release_type",
}

LANGUAGE_MAPPING = {
    "radarr": {
        -1: "Any",
        -2: "Original",
        0: "Unknown",
        1: "English",
        2: "French",
        3: "Spanish",
        4: "German",
        5: "Italian",
        6: "Danish",
        7: "Dutch",
        8: "Japanese",
        9: "Icelandic",
        10: "Chinese",
        11: "Russian",
        12: "Polish",
        13: "Vietnamese",
        14: "Swedish",
        15: "Norwegian",
        16: "Finnish",
        17: "Turkish",
        18: "Portuguese",
        19: "Flemish",
        20: "Greek",
        21: "Korean",
        22: "Hungarian",
        23: "Hebrew",
        24: "Lithuanian",
        25: "Czech",
        26: "Hindi",
        27: "Romanian",
        28: "Thai",
        29: "Bulgarian",
        30: "Portuguese_br",
        31: "Arabic",
        32: "Ukrainian",
        33: "Persian",
        34: "Bengali",
        35: "Slovak",
        36: "Latvian",
        37: "Spanish_latino",
        38: "Catalan",
        39: "Croatian",
        40: "Serbian",
        41: "Bosnian",
        42: "Estonian",
        43: "Tamil",
        44: "Indonesian",
        45: "Telugu",
        46: "Macedonian",
        47: "Slovenian",
        48: "Malayalam",
        49: "Kannada",
        50: "Albanian",
        51: "Afrikaans",
    },
    "sonarr": {
        0: "Unknown",
        1: "English",
        2: "French",
        3: "Spanish",
        4: "German",
        5: "Italian",
        6: "Danish",
        7: "Dutch",
        8: "Japanese",
        9: "Icelandic",
        10: "Chinese",
        11: "Russian",
        12: "Polish",
        13: "Vietnamese",
        14: "Swedish",
        15: "Norwegian",
        16: "Finnish",
        17: "Turkish",
        18: "Portuguese",
        19: "Flemish",
        20: "Greek",
        21: "Korean",
        22: "Hungarian",
        23: "Hebrew",
        24: "Lithuanian",
        25: "Czech",
        26: "Arabic",
        27: "Hindi",
        28: "Bulgarian",
        29: "Malayalam",
        30: "Ukrainian",
        31: "Slovak",
        32: "Thai",
        33: "Portuguese_br",
        34: "Spanish_latino",
        35: "Romanian",
        36: "Latvian",
        37: "Persian",
        38: "Catalan",
        39: "Croatian",
        40: "Serbian",
        41: "Bosnian",
        42: "Estonian",
        43: "Tamil",
        44: "Indonesian",
        45: "Macedonian",
        46: "Slovenian",
        -2: "Original",
    },
}

INDEXER_FLAG_MAPPING = {
    "radarr": {
        1: "freeleech",
        2: "halfleech",
        4: "double_upload",
        32: "internal",
        128: "scene",
        256: "freeleech_75",
        512: "freeleech_25",
        2048: "nuked",
        8: "ptp_golden",
        16: "ptp_approved",
    },
    "sonarr": {
        1: "freeleech",
        2: "halfleech",
        4: "double_upload",
        8: "internal",
        16: "scene",
        32: "freeleech_75",
        64: "freeleech_25",
        128: "nuked",
    },
}

RELEASE_TYPE_MAPPING = {
    "sonarr": {
        0: "none",
        1: "single_episode",
        2: "multi_episode",
        3: "season_pack",
    }
}

SOURCE_MAPPING = {
    "radarr": {
        1: "cam",
        2: "telesync",
        3: "telecine",
        4: "workprint",
        5: "dvd",
        6: "tv",
        7: "web_dl",
        8: "webrip",
        9: "bluray",
    },
    "sonarr": {
        1: "television",
        2: "television_raw",
        3: "web_dl",
        4: "webrip",
        5: "dvd",
        6: "bluray",
        7: "bluray_raw",
    },
}

QUALITY_MODIFIER_MAPPING = {
    "radarr": {
        0: "none",
        1: "regional",
        2: "screener",
        3: "rawhd",
        4: "brdisk",
        5: "remux",
    }
}

QUALITY_SIZE_NAME_MAPPING = {
    "movie": "Movie",
    "anime": "Anime",
    "sqp-streaming": "SQP Streaming",
    "sqp-uhd": "SQP UHD",
    "series": "Series",
}

DEFAULT_TAGS = [
    "Sonarr",
    "Radarr",
    "Release Title",
    "Resolution",
    "Source",
    "Language",
    "Release Group",
    "Indexer Flag",
    "Quality Modifier",
    "Release Type",
    "French",
    "German",
    "Default",
    "SQP",
    "Anime",
]
